spring.application.name=secure-file-vault
server.port=8080

# Logging Configurations
logging.level.root=INFO
logging.level.com.saimanikantha.securefilevault=DEBUG

# Auto-Configuration Exclusions (to run without DB configuration in Phase 0.5/Phase 1)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Actuator Configurations
management.endpoints.web.exposure.include=health
